exports.coffeeMachines = [
  {
    sku_code: "CM001",
    product_type: "COFFEE_MACHINE_SMALL",
    water_line_compatible: false,
    model: "base",
  },
  {
    sku_code: "CM002",
    product_type: "COFFEE_MACHINE_SMALL",
    water_line_compatible: false,
    model: "premium",
  },
  {
    sku_code: "CM003",
    product_type: "COFFEE_MACHINE_SMALL",
    water_line_compatible: true,
    model: "deluxe",
  },
  {
    sku_code: "CM101",
    product_type: "COFFEE_MACHINE_LARGE",
    water_line_compatible: false,
    model: "base",
  },
  {
    sku_code: "CM102",
    product_type: "COFFEE_MACHINE_LARGE",
    water_line_compatible: true,
    model: "premium",
  },
  {
    sku_code: "CM103",
    product_type: "COFFEE_MACHINE_LARGE",
    water_line_compatible: true,
    model: "deluxe",
  },
  {
    sku_code: "EM001",
    product_type: "ESPRESSO_MACHINE",
    water_line_compatible: false,
    model: "base",
  },
  {
    sku_code: "EM002",
    product_type: "ESPRESSO_MACHINE",
    water_line_compatible: false,
    model: "premium",
  },
  {
    sku_code: "EM003",
    product_type: "ESPRESSO_MACHINE",
    water_line_compatible: true,
    model: "deluxe",
  },
];

exports.coffeePods = [
  {
    sku_code: "CP001",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 1,
  },
  {
    sku_code: "CP003",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 3,
  },
  {
    sku_code: "CP011",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 1,
  },
  {
    sku_code: "CP013",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 3,
  },
  {
    sku_code: "CP021",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_PSL",
    pack_size: 1,
  },
  {
    sku_code: "CP023",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_PSL",
    pack_size: 3,
  },
  {
    sku_code: "CP031",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_MOCHA",
    pack_size: 1,
  },
  {
    sku_code: "CP033",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_MOCHA",
    pack_size: 3,
  },
  {
    sku_code: "CP041",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_HAZELNUT",
    pack_size: 1,
  },
  {
    sku_code: "CP043",
    product_type: "COFFEE_POD_SMALL",
    coffee_flavor: "COFFEE_FLAVOR_HAZELNUT",
    pack_size: 3,
  },
  {
    sku_code: "CP101",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 1,
  },
  {
    sku_code: "CP103",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 3,
  },
  {
    sku_code: "CP111",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 1,
  },
  {
    sku_code: "CP113",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 3,
  },
  {
    sku_code: "CP121",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_PSL",
    pack_size: 1,
  },
  {
    sku_code: "CP123",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_PSL",
    pack_size: 3,
  },
  {
    sku_code: "CP131",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_MOCHA",
    pack_size: 1,
  },
  {
    sku_code: "CP133",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_MOCHA",
    pack_size: 3,
  },
  {
    sku_code: "CP141",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_HAZELNUT",
    pack_size: 1,
  },
  {
    sku_code: "CP143",
    product_type: "COFFEE_POD_LARGE",
    coffee_flavor: "COFFEE_FLAVOR_HAZELNUT",
    pack_size: 3,
  },
  {
    sku_code: "EP003",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 3,
  },
  {
    sku_code: "EP005",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 5,
  },
  {
    sku_code: "EP007",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_VANILLA",
    pack_size: 7,
  },
  {
    sku_code: "EP013",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 3,
  },
  {
    sku_code: "EP015",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 5,
  },
  {
    sku_code: "EP017",
    product_type: "ESPRESSO_POD",
    coffee_flavor: "COFFEE_FLAVOR_CARAMEL",
    pack_size: 7,
  },
];
